config/routes.rb
Rails.application.routes.draw do

  resources :gists
  get 'welcome/index'
  get 'sessions/new'
  get 'users/new'

  devise_for :users, controllers: {sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists
    resources :badges
  end

  resources :feedback

  resources :badges

  resources :users_badges

  root 'welcome#index'
end
# For details on the DSL available within this file, see https://guides.r

app/models/admin.rb
class Admin < User
    validates :first_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :text, presence: true
  validate :answers_limit, on: :create

  scope :correct, -> {where(correct: true)}

  private

  def answers_limit
    if question.answers.count >= 4
      errors.add(:question, "Ответов должно быть не больше 4")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :users_badges, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :desc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
    belongs_to :question
    belongs_to :user
end
  

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"
  belongs_to :category

  has_many :questions, dependent: :destroy
  has_many :tests_users, dependent: :destroy
  has_many :users, through: :tests_users

  validates :title, presence: true,
                    uniqueness: { scope: :level }
                    
  validates :level, numericality: { only_integer: true, greater_than: 0 },
                    uniqueness: { scope: :title }

  scope :easy, -> {where(level: 0..1)}
  scope :medium, -> {where(level: 2..4)}
  scope :hard, -> {where(level: 5..Float::INFINITY)}
  scope :sort_by_category, -> (category_title) {joins(:category)
        .where(categories: {title: category_title})
        .order(title: :desc)}
  scope :by_level, -> (level) {where(level: level)}

  def self.sort_tests_by_category(category)
    Test.sort_by_category(category)
        .order(title: :desc)
        .pluck(:title)
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  # before_validation :before_validation_answer_ids, on: :update

  # validate :answers_limit?, on: :update

  CHECKPOINT_RESULT = 85


  def time_remaining
    time = (self.created_at + self.test.timer - Time.now).round(0)
  end

  def time_over?
    time_remaining <= 0
  end

  def completed?
    self.time_over? && self.test.timer != 0 || current_question.nil?
  end

  def accept!(answer_ids)
        
    self.correct_questions += 1 if correct_answer?(answer_ids)
  
    self.current_question = next_question
    save!
  end

  def test_result
    @result = ((self.correct_questions / test.questions.count.to_f) *100).round(0)
  end

  def done?
    test_result > CHECKPOINT_RESULT
  end

  def number_current_question
    test.questions.order(:id).where('id < ?', self.current_question.id).count + 1
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids.present?
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: "Test", foreign_key: "author_id"
  has_many :tests_users
  has_many :tests, through: :tests_users, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :users_badges
  has_many :badges, through: :users_badges, dependent: :destroy

  validates :email, presence: true,
                    uniqueness: { scope: :email, message: "данная почта уже зарегистрированна"},
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: "не верный формат почты"}


  def user_tests_by_level(level)
    tests.by_level(level)
  end

  def tests_user(test)
    tests_users.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/users_badge.rb
class UsersBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_user, only: %i[create]

  def set_test_user
    @test_user = TestsUser.find(params[:id])
  end

  def create
    result = GistQuestionService.new(@test_user.current_question).call      
    
    if result.success?
        current_user.gists.create!(question: @test_user.current_question, url: result.url)
        flash[:notice] = "#{I18n.t('.success')} - #{view_context.link_to(I18n.t('.link'), result.url)}"
    else
        flash[:alert] = I18n.t('.failure')
    end
      redirect_to @test_user
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.tests_user(@test)
  end

  private
  
  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def github_url(author, repo)
      link_to "Проект", "https://github.com/#{author}/#{repo}", target: '_blank'
    end
    
    def current_year
      Date.current.year
    end
    
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    if test.new_record?
      I18n.t('.new_create_test')
    else
      I18n.t('.edit_test', title: test.title)
    end
  end
end

app/helpers/tests_users_helper.rb
module TestsUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
  <%= render 'shared/nav' %>
  <div class="container">
  <%= render 'shared/flash' %>
  <%= yield %>
  </div>
  </body>
  <%= render 'shared/footer' %>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
<%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do %>

  <h2> Найдена ошибка </h2>

  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-primary" role="alert">
  <%= content_tag :p, message.html_safe, class: "flash #{key}" %>
<% end %>
</div>

app/views/shared/_footer.html.erb
<div class="fixed-bottom">
<p>Это приложение позволит вам создавать тесты и проходить их!<br>
    <%= github_url('MaxKoleshatov', 'test-guru') %><br>
    Автор: Maxim Koleshatov<br>
    Это приложение является учебным проектом онлайн школы <a target="_blank" href="https://thinknetica.com/">Thinknetica</a><br>
    <%= current_year %><br>
</p>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
<%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

<span class="navbar-text">
  <% if user_signed_in? %>
   <p class='nav user'><%= t('.welcome')%>, <b><%= current_user.email %></b>  Guru </p>
   <p class='nav_user'><%= link_to t('.log_out'), destroy_user_session_path, method: :delete %></p>
   <p class='nav_user'><%= link_to "Обратная связь", feedback_index_path %></p>
    <% if current_user.admin?%>
     <p class="nav user"><%= link_to 'Admin', admin_tests_path %></p>
     <p class="nav user"><%= link_to 'Gists', admin_gists_path %></p>
     <p class="nav user"><%= link_to 'Все награды', admin_badges_path %></p>
    <% else %>
     <p class="nav user"><%= link_to 'Мои награды', users_badges_path %></p>
    <% end %>
  <% end %>

</span>
</nav>