config/routes.rb
Rails.application.routes.draw do

  resources :gists
  get 'welcome/index'
  get 'sessions/new'
  get 'users/new'

  devise_for :users, controllers: {sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :tests_users, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
    resources :gists
    resources :badges
  end

  resources :feedback

  resources :badges

  resources :users_badges

  root 'welcome#index'
end
# For details on the DSL available within this file, see https://guides.r

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[edit update show destroy]
  
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
 
  def show; end

  def new
    @question = Question.new
  end
  
  def create
    question = @test.questions.build(questions_params)

    if question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(questions_params)
      redirect_to admin_question_path(@question.test)
    else
      render :edit
    end
  end
  
  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def questions_params
    params.require(:question).permit(:body, :test_id)
  end

  def rescue_with_question_not_found
    render plain: "Нет такого вопроса"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{@test.title} Question"
    else
      "Edit #{@question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question] do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p> 
    <%= form.label t('.body') %><br>
    <%= form.text_field :body %>
  </p><br>
     
  <p>
    <%= form.submit%>
  </p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body%></td>
  <td><%= link_to t('.show_question'), admin_question_path(question) %></td>
  <td><%= link_to t('.edit_question'), edit_admin_question_path(question) %></td>
  <td><%= link_to t('.delete_question'), admin_question_path(question), method: :delete %></td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form'%>

<%= link_to 'Назад', admin_test_path(@question.test.id) %>

app/views/admin/questions/index.html.erb
  <h1>Все Вопросы теста - "<%= @test.title %>" </h1>
  <% if @test.questions.present? %>
    <table>
      <tr>
        <th>Вопросы</th>
        <th colspan="3"> Действия</th>
      </tr>

      <%= render @questions %>
    </table>
  <% else%>
    <p> render plain:"У вас нет тестов"</p>
  <% end%>

  <p></p>

  <%= link_to 'Создать новый вопрос', new_test_question_path(@test) %> 

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form'%>

  
<%= link_to 'Назад', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%=t('.header', title: @question.test.title)%></h1>

<p><%= @question.body%></p>

<h2> <%=t('.answers')%> </h2>

<ol>
<%= render @question.answers%>
</ol>

<%= link_to t('.create_new_answer'), new_admin_question_answer_path(@question) %> |

<%= link_to t('.edit_answer'), edit_admin_question_path(@question) %> |

<%= link_to t('.delete_answer'), admin_question_path(@question), method: :delete %> |

<%= link_to t('.back'), admin_test_path(@question.test.id) %>